package config

// HTTP Status Codes
const (
	OK                    = 200
	CREATED               = 201
	UPDATED               = 202
	BAD_REQUEST           = 400
	UNAUTHORIZED          = 401
	ACCESS_FORBIDDEN      = 403
	NOT_FOUND             = 404
	INTERNAL_SERVER_ERROR = 500
)

// Response Types
const (
	// Success Types
	TYPE_DEFAULT              = "DEFAULT"
	TYPE_LOGIN                = "LOGIN"
	TYPE_SIGNUP               = "SIGNUP"
	TYPE_LOGOUT               = "LOGOUT"
	TYPE_PROFILE              = "PROFILE"
	TYPE_UPDATE_PROFILE       = "UPDATE_PROFILE"
	TYPE_CHANGE_PASSWORD      = "CHANGE_PASSWORD"
	TYPE_RESET_PASSWORD       = "RESET_PASSWORD"
	TYPE_SEND_OTP             = "SEND_OTP"
	TYPE_VERIFY_OTP           = "VERIFY_OTP"
	TYPE_MAIL_SENT            = "MAIL_SENT"
	TYPE_VERIFY_TOKEN         = "VERIFY_TOKEN"
	TYPE_ADMIN_LOGIN          = "ADMIN_LOGIN"
	TYPE_USER_LOGOUT          = "USER_LOGOUT"
	TYPE_BLOCK_USER           = "BLOCK_USER"
	TYPE_UNBLOCK_USER         = "UNBLOCK_USER"
	TYPE_NOTIFICATION_DELETED = "NOTIFICATION_DELETED"

	// Error Types
	TYPE_ERROR                      = "ERROR"
	TYPE_UNAUTHORIZED_ACCESS        = "UNAUTHORIZED_ACCESS"
	TYPE_INTERNAL_SERVER_ERROR_TYPE = "INTERNAL_SERVER_ERROR"
	TYPE_BAD_TOKEN                  = "BAD_TOKEN"
	TYPE_TOKEN_EXPIRED              = "TOKEN_EXPIRED"
	TYPE_SESSION_EXPIRED            = "SESSION_EXPIRED"
	TYPE_BLOCKED                    = "BLOCKED"
	TYPE_DEACTIVATED                = "DEACTIVATED"
	TYPE_DELETED                    = "DELETED"
	TYPE_INCORRECT_PASSWORD         = "INCORRECT_PASSWORD"
	TYPE_PASSWORD_MISMATCH          = "PASSWORD_MISMATCH"
	TYPE_EMAIL_NOT_REGISTERED       = "EMAIL_NOT_REGISTERED"
	TYPE_EMAIL_ALREADY_EXIST        = "EMAIL_ALREADY_EXIST"
	TYPE_EMAIL_NOT_VERIFIED         = "EMAIL_NOT_VERIFIED"
	TYPE_INVALID_OLD_PASSWORD       = "INVALID_OLD_PASSWORD"
	TYPE_OTP_EXPIRED                = "OTP_EXPIRED"
	TYPE_INVALID_OTP                = "INVALID_OTP"
	TYPE_EXCEED_OTP_LIMIT           = "EXCEED_OTP_LIMIT"
	TYPE_USER_NOT_FOUND             = "USER_NOT_FOUND"
	TYPE_PROFILE_NOT_COMPLETED      = "PROFILE_NOT_COMPLETED"
	TYPE_SAME_PASSWORD              = "SAME_PASSWORD"
	TYPE_PASSWORD_REUSE             = "PASSWORD_REUSE"
	TYPE_MOBILE_NO_NOT_VERIFIED     = "MOBILE_NO_NOT_VERIFIED"
	TYPE_MOBILE_NO_ALREADY_EXIST    = "MOBILE_NO_ALREADY_EXIST"
)

const (
	BASIC_USERNAME = "fiber"
	BASIC_PASSWORD = "fiber@123"
)


const (
	USERS_COLLECTION= "users"
	ADMIN_COLLECTION = "admins"
	LOGIN_SESSIONS_COLLECTION = "login_sessions"
)