// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://example.com/terms",
        "contact": {
            "name": "Aman Dixit",
            "email": "aman.dixit@appinevtiv.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all users with search",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "List users",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search by name",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "1",
                            "2",
                            "3"
                        ],
                        "type": "string",
                        "default": "1",
                        "description": "Device OS: 1-Android, 2-iOS, 3-WEB",
                        "name": "platform",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "Asia/Kolkata",
                        "description": "Time zone",
                        "name": "timezone",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Time zone offset",
                        "name": "offset",
                        "in": "header"
                    },
                    {
                        "enum": [
                            "en",
                            "hi"
                        ],
                        "type": "string",
                        "default": "en",
                        "description": "Language: en, hi",
                        "name": "accept-language",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "v1",
                        "description": "App version",
                        "name": "appversion",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "v1",
                        "description": "Route version",
                        "name": "routeversion",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_addixit1_fiber-boilerplate_internal_config.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_addixit1_fiber-boilerplate_internal_config.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "basicAuth": []
                    }
                ],
                "description": "Create a new user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "Create user",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_modules_user_v1.CreateUserDTO"
                        }
                    },
                    {
                        "enum": [
                            "1",
                            "2",
                            "3"
                        ],
                        "type": "string",
                        "default": "1",
                        "description": "Device OS: 1-Android, 2-iOS, 3-WEB",
                        "name": "platform",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "Asia/Kolkata",
                        "description": "Time zone",
                        "name": "timezone",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Time zone offset",
                        "name": "offset",
                        "in": "header"
                    },
                    {
                        "enum": [
                            "en",
                            "hi"
                        ],
                        "type": "string",
                        "default": "en",
                        "description": "Language: en, hi",
                        "name": "accept-language",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "v1",
                        "description": "App version",
                        "name": "appversion",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "default": "v1",
                        "description": "Route version",
                        "name": "routeversion",
                        "in": "header"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_addixit1_fiber-boilerplate_internal_config.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_addixit1_fiber-boilerplate_internal_config.APIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_addixit1_fiber-boilerplate_internal_config.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_addixit1_fiber-boilerplate_internal_config.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_modules_user_v1.CreateUserDTO": {
            "type": "object",
            "required": [
                "email",
                "name"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "aman@gmail.com"
                },
                "name": {
                    "type": "string",
                    "example": "Aman"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3010",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Fiber Boilerplate",
	Description:      "Production ready Fiber backend",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
